// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: cherkesgiller (https://sketchfab.com/cherkesgiller)
// License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
// Source: https://sketchfab.com/3d-models/abstract-design-5f61a7b5eaa64af093d7cd721c9ef5ad
// Title: Abstract Design
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model2(props) {
//   const { nodes, materials } = useGLTF('/abstract_design.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.VoronoiDynoBake_Material_0.geometry}
//         material={materials.Material}
//         rotation={[-Math.PI / 2, 0, 0]}
//         scale={100}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/abstract_design.glb')
