/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: ayvlasov (https://sketchfab.com/ayvlasov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/triplet-structure-f0a0bb31474748c8bb933a98656a60e2
Title: Triplet Structure
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Triplet_0.geometry} material={materials.MaterialTriplet} position={[0, 0, 2]} />
        <mesh geometry={nodes.Triplet001_0.geometry} material={materials['MaterialTriplet.001']} position={[0, 0, 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
